### PR TITLE
🇻🇳create Vietnamese translation

### PR DESCRIPTION
**Pull request by hungphongbk**

### CODE REVIEW

**Comment by kazupon** [comment]
/ping @phanan 
Can you review this PR?

**Comment by hungphongbk** [comment]
hi @kazupon, this PR is still in-progress. @phanan can u help me review pieces of docs I've translated?

**Comment by phanan** [comment]
@kazupon @hungphongbk Please ping me when the translation is done. I think it should be easier that way, instead of back-and-forth reviewing/fixing.

**Comment by hungphongbk** [comment]
/ping @chlutch @tuannda how about translating this PR? :v

**Comment by hungphongbk** [comment]
/ping @phanan the translation has done but @yyx990803 closed it

**Pull request closed without merging**
