### PR TITLE
docs: [KR] Translation update

### PR DESCRIPTION
**Pull request by ERTuringLee**

### CODE REVIEW

**Comment by kazupon** [comment]
Thank you for your translation!

As said of the following refer, basically we are no hosting translations in the project repos.

https://github.com/vuejs/vue-cli/pull/2295#issuecomment-414517826
https://gist.github.com/yyx990803/628143350cc7ff705d1364ecc70e2cca

As said of the following refer, basically we are no hosting translations in the project repos.
If you are committed to keep the translation up-to-date for the long run, we can accept the your PR.

Do you think you can do that?

**Comment by ERTuringLee** [comment]
Oh, I see. I read the refer and I understand. I want to translate vue documentation because I love vue.js. Even If your team not support hosting a korean translation documentation, I will translate vue documentation to google docs or my blog for my country.

**Comment by kazupon** [comment]
okay :)
I seem that `vuejs-kr` have `vue-loader` repo.
https://github.com/vuejs-kr

If it's possible host at vuejs-kr  organaization,  at first, you'd better host in there. /cc @ChangJoo-Park

**Comment by ERTuringLee** [comment]
Okay :) Thank you!

**Comment by kazupon** [comment]
@ERTuringLee 
Is there anything update?
if no update, I'll close this issue.

**Comment by ERTuringLee** [comment]
ok

**Pull request closed without merging**
