### PR TITLE
Setup eslint config for test files

### PR DESCRIPTION
**Pull request by sudo-suhas**
Add `.eslintrc` for test folder with `env` as `"mocha"`. Fix eslint errors in test folders.

### CODE REVIEW

**Comment by sudo-suhas** [comment]
What do you guys think of setting up [`lint-staged`](https://github.com/okonet/lint-staged) with git pre-commit hook? It can run eslint on the modified files before commit.

**Comment by gucong3000** [comment]
> setting up lint-staged with git pre-commit hook
I 'd like make a PR.

**Comment by sudo-suhas** [comment]
> I 'd like make a PR.

Hey @gucong3000 please don't mind, but that sentence is a little ambiguous. Are you saying you'd like it if I made a PR setting up `lint-staged` or are you saying you will make a PR for it?

**Comment by gucong3000** [comment]
both OK

**Comment by yyx990803** [comment]
@sudo-suhas feel free to submit a PR for `lint-staged`!

**Comment by sudo-suhas** [comment]
@yyx990803 Made a PR for `lint-staged` - #914

**Pull request merged**
