### PR TITLE
Add doc for `stylelint`

### PR DESCRIPTION
**Pull request by gucong3000**
Related: #303
- [x] en
- [x] zh
- [x] ru

### CODE REVIEW

**Comment by gucong3000** [comment]
@yyx990803 
If you like this PR, I will find someone to help translate it to Russian.

**Comment by gucong3000** [comment]
Anyone make any comments?

**Comment by kazupon** [comment]
/ping @Alex-Sokolov 
Can you help translation about it?

**Comment by gucong3000** [comment]
Does anyone have any comments on the Chinese and English parts?

**Comment by kazupon** [comment]
On second thought 🤔, I think that we don't have to put it to Vue Loader documentation, because stylelint is not necessarily required linter and it optional set with user.

**Comment by Alex-Sokolov** [comment]
@kazupon done (https://github.com/gucong3000/vue-loader/pull/1), needed merge from @gucong3000

P.S.: Can you merge https://github.com/vuejs/vue-loader/pull/1342

**Comment by gucong3000** [comment]
> stylelint is not necessarily required linter

I don't quite understand why the linter of CSS code is less important than JS?
CSS code is as important to the project as JS, so they also need linter

**Comment by gucong3000** [comment]
Stylelint is used by [Facebook](https://code.fb.com/open-source/improving-css-quality-at-facebook-and-beyond/), [Wikipedia](https://github.com/wikimedia/stylelint-config-wikimedia) and [GitHub](https://github.com/primer/primer).

create-react-app [will support it](https://github.com/facebook/create-react-app/pull/1216).

Right now it is the [most popular CSS linter](http://www.npmtrends.com/csslint-vs-csscomb-vs-stylelint-vs-sass-lint).

**Comment by kazupon** [comment]
@gucong3000 
Yeah, Linter of CSS codes is very important. 
However, I think should not include how to setting of Stylelint, due to already exist as Stylelint documentation.
https://github.com/webpack-contrib/stylelint-webpack-plugin

**Comment by gucong3000** [comment]
> due to already exist as Stylelint documentation.
https://github.com/webpack-contrib/stylelint-webpack-plugin

It does not contain `*.vue` file configuration.

**Comment by yyx990803** [comment]
I think this is good to have. Thanks!

**Comment by kazupon** [comment]
@yyx990803 
okay! I got it!

**Pull request merged**
