### PR TITLE
Support load postcss config by "config.path"

### PR DESCRIPTION
**Pull request by smadey**
ref #944

### CODE REVIEW

**Comment by japboy** [comment]
any progress?

**Comment by LinusBorg** [comment]
No.

**Comment by japboy** [comment]
what else is necessary to merge this PR?

**Comment by smadey** [comment]
Necessary in nuxt.js app.
I want auto load postcss.config.js at srcDir, and it doesn't work.

**Comment by LinusBorg** [comment]
A test would be helpful.

**Comment by smadey** [comment]
Test project: [nuxt-postcss-demo](https://github.com/smadey/nuxt-postcss-demo)
Note [this line](https://github.com/smadey/nuxt-postcss-demo/blob/master/src/nuxt.config.js#L33)

**Comment by LinusBorg** [comment]
Sorry, I meant a unit test in vue-loader's test suite. But that Test project will also be helpful to take it for a quick spin!

**Comment by japboy** [comment]
i found this doesnt work properly.

if `<style>` has `lang="postcss"` attribute, the build process fails. if the attribute doesnt exist, it works although postcss wont be transpiled to pure css.

i think this issue should be fixed before the pr gets merged.

**Comment by yyx990803** [comment]
Thanks for the PR - I went with a slightly different API in 94d374b318be33c91306631d0f1482f61a00e63d

To configure the path you can now do

``` js
options: {
  postcss: {
    configRoot: 'the directory to load config file from'
  }
}
```

@japboy note the value should be a directory to look for config files, not an exact file path.

**Comment by smadey** [comment]
@yyx990803 
希望能和 [postcss-loader](https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L79) 对齐，在 nuxt.js 应用场景下，postcss 的配置可能会被同时用于 postcss-loader 或者 vue-loader

**Comment by yyx990803** [comment]
Adjusted to be consistent with `postcss-loader` in 13.2.1: https://github.com/vuejs/vue-loader/releases/tag/v13.2.1

**Comment by kdex** [comment]
For anyone reading this thread: The API has changed, though I don't think it's documented yet. You can specify the configuration path in your webpack configuration by inserting this into the `module.rules` array property:
```js
{
	test: /\.vue$/,
	loader: "vue-loader",
	options: {
		postcss: {
			config: {
				path: "src/css"
			}
		}
	}
}
```

**Pull request closed without merging**
