### PR TITLE
Update custom-blocks.md

### PR DESCRIPTION
**Pull request by camille666**
this is vue-loader，not vue，in my opinion.

### CODE REVIEW

**Comment by camille666** [comment]
when I try to play the custom-blocks,I have a question.
if I want to use custom-blocks and get single css file, how can i achieve it?
var ExtractTextPlugin1 = require("extract-text-webpack-plugin");
var ExtractTextPlugin2 = require("extract-text-webpack-plugin");

module.exports = {
  entry: './myvu.js',
  output: {
    path: __dirname,
    filename: 'bundle.js'
  },
  devtool: "inline-source-map",
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            css: ExtractTextPlugin1.extract({
              use: 'css-loader',
              fallback: 'vue-style-loader' // 这是vue-loader的依赖，所以如果使用npm3，则不需要显式安装。
            })
          }
        }
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            // 提取 <docs> 中的内容为原始文本
            'docs': ExtractTextPlugin2.extract('raw-loader')
          }
        }
      }
    ]
  },
  resolve: {
    alias: {
      vue$: 'vue/dist/vue.js', //vue$表示精确匹配
    }
  },
  plugins: [
    new ExtractTextPlugin1("style.css"),
    new ExtractTextPlugin2("docs.md")
  ]
}

**Comment by camille666** [comment]
the result is not what i want，because style.css and docs.md are same.
I hope docs.md just include sth about docs, and style.css just include sth about css.

**Comment by Jinjiang** [comment]
> when I try to play the custom-blocks,I have a question.

Do you mean the config `loader: 'vue'` leads to this problem? Or just another isolated question without your PR?

**Comment by Jinjiang** [comment]
@vuejs/vue-loader-vueify I think it's not only for `zh-cn` docs. Because [automatic `-loader` module name extension removed](https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed) from webpack 2.
Thanks.

**Comment by kazupon** [comment]
@camille666 @Jinjiang 
I hope that you will update it for other languages, because other translation maintenainer will be get easier and keep docs quality. 🙏

**Pull request closed without merging**
