### PR TITLE
keep path of source file in source map

### PR DESCRIPTION
**Pull request by Elevista**
In chrome devtool

Before
before

After
after

### CODE REVIEW

**Comment by Elevista** [comment]
@kazupon sure. [https://github.com/Elevista/temp](https://github.com/Elevista/temp)
npm run start will run server with webpack build

**Comment by kazupon** [comment]
@Elevista 
Thanks!
It looks good to me.

/ping @yyx990803
Please check it!

**Comment by weizhenye** [comment]
I'm guessing this PR cause a bug about path.

I have followed [this tutorial](https://404forest.com/2017/02/22/use-karma-mocha-kits-to-write-unit-tests-for-vue-component/) to set up a test workflow with friendly coverage report. With `vue-loader@13.0.2`，everything works fine as expected, however when I update to `vue-loader@13.0.3`, the path of `.vue` files showed in html coverage report is wrong.
 
**Before:**

before

before-demo

**After:**

after

after-demo

It seems the path of `.vue` files is repeated and gets a wrong result.


```
Unable to lookup source: F:\test\src\views\src\views\Demo.vue(ENOENT: no such file or directory, open 'F:\test\src\views\src\views\Demo.vue')
Error: Unable to lookup source: F:\test\src\views\src\views\Demo.vue(ENOENT: no such file or directory, open 'F:\test\src\views\src\views\Demo.vue')
    at Context.defaultSourceLookup [as sourceFinder] (F:\test\node_modules\istanbul-lib-report\lib\context.js:15:15)
    at Context.getSource (F:\test\node_modules\istanbul-lib-report\lib\context.js:74:17)
    at Object.annotateSourceCode (F:\test\node_modules\istanbul-reports\lib\html\annotator.js:175:38)
    at HtmlReport.onDetail (F:\test\node_modules\istanbul-reports\lib\html\index.js:217:39)
    at LcovReport.(anonymous function) [as onDetail] (F:\test\node_modules\istanbul-reports\lib\lcov\index.js:24:24)
    at Visitor.(anonymous function) [as onDetail] (F:\test\node_modules\istanbul-lib-report\lib\tree.js:34:30)
    at ReportNode.Node.visit (F:\test\node_modules\istanbul-lib-report\lib\tree.js:123:17)
    at F:\test\node_modules\istanbul-lib-report\lib\tree.js:116:23
    at Array.forEach ()
    at visitChildren (F:\test\node_modules\istanbul-lib-report\lib\tree.js:115:32)
    at ReportNode.Node.visit (F:\test\node_modules\istanbul-lib-report\lib\tree.js:126:5)
    at F:\test\node_modules\istanbul-lib-report\lib\tree.js:116:23
    at Array.forEach ()
    at visitChildren (F:\test\node_modules\istanbul-lib-report\lib\tree.js:115:32)
    at ReportNode.Node.visit (F:\test\node_modules\istanbul-lib-report\lib\tree.js:126:5)
    at Tree.visit (F:\test\node_modules\istanbul-lib-report\lib\tree.js:158:20)
```

**Comment by weizhenye** [comment]
@Elevista
I checked every commits between v13.0.2 and v13.0.3, I can be confirm this issue is introduced by this PR.

Reproduce:
1. Download [this gist](https://gist.github.com/anonymous/fe035171c13484e671cb4ce8ad5b0f2a) ZIP.
2. Move `app.js` to `src/app.js`.
3. Move `Demo.vue` to `src/views/Demo.vue`.
4. Move `test.js` to `test/test.js`.
5. Move `Demo.spec.js` to `test/Demo.spec.js`.
6. `npm i`
7. `npm test`
8. Open `coverage/index.html`

**Comment by Elevista** [comment]
@weizhenye I exactly got what I missed
image
I'll solve this. thank you

**Comment by Elevista** [comment]
@weizhenye 
I found istanbul-instrumenter-loader references `sourceRoot` property of source map
https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/e419a634d2f954566cfb1c444f4933947343ca17/src/util.js#L30
I provide it so, the problem solved

**Pull request merged**
