### PR TITLE
fix: keep build stable when run in a different path

### LINKED ISSUE #2028: Build is unstable when project is build in a different path
https://github.com/atk4/ui/blob/dedb4cea3191e45ba2334ad48c0f98c6d25edf32/.github/workflows/test-unit.yml#L344 hack is needed to make babel build stable, otherwise a variable name in the resulting build is containing the resolved local path, making the build unstable

how to reproduce:
1. checkout https://github.com/atk4/ui
2. cd into js/ dir
3. run npm install (without the patch from above applied) and `npm run build`
4. notice the git changes in ../public/js dir containing a local path

### PR DESCRIPTION
**Pull request by mvorisek**
fix #2028, full credit goes to @alexander-akait, thank you!

I have tested this fix and I can confirm the original issue is fixed with it.

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
@yyx990803 this is the correct fix for stable file content

**Comment by mvorisek** [comment]
Hi @sodatea, would it be possible to merge this PR, please?

**Comment by sodatea** [comment]
Sure.

I'm away from home today, though. I'll take a look and try to cut a new release this weekend.

**Review by sodatea — APPROVED** [review]

**Comment by mvorisek** [comment]
@sodatea the webpack 4 tests timeout for some unknown/unrelated reason, but otherwise the tests pass - can a new release be tagged?

**Comment by sodatea** [comment]
Fixed and released.

**Pull request merged**
