### PR TITLE
Bump dependencies(minor/patch)

### PR DESCRIPTION
**Pull request by sudo-suhas**
#### Dependencies

|Package               |Current |Latest |Reason |
|----------------------|--------|-------|-------|
|postcss               |6.0.6   |6.0.8  |Fix Node.js 4.2.2 support, Fix base64 decoding for old Node.js and browser[`➚`](https://github.com/postcss/postcss/blob/master/CHANGELOG.md)|
|resolve               |1.3.3   |1.4.0  |fix when package.json main = ‘.’, add `preserveSymlinks` option[`➚`](https://github.com/substack/node-resolve/compare/v1.3.3...v1.4.0)|

#### Dev-Dependencies

|Package               |Current |Latest |Reason |
|----------------------|--------|-------|-------|
|coffee-script         |1.12.6  |1.12.7 |Fix regressions related to chained func calls and indented return and throw arguments[`➚`](http://coffeescript.org/#changelog)|
|js-yaml                |3.9.0  |3.9.1  |Ensure stack is present for custom errors in node 7.+[`➚`](https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md)|
|inject-loader         |3.0.0   |3.0.1  |set compact to false and provide filename to babel, Add webpack 3 peerDependency[`➚`](https://github.com/plasticine/inject-loader/compare/v3.0.0...v3.0.1)|
|vue                   |2.4.1   |2.4.2  |[`➚`](https://github.com/vuejs/vue/releases)|
|vue-server-renderer   |2.4.1   |2.4.2  |Not sure|
|vue-template-compiler |2.4.1   |2.4.2  |Not sure|
|webpack               |3.3.0   |3.4.1  |Features, bug fixes, perf[`➚`](https://github.com/webpack/webpack/releases)|

**NOTE:** No major version update is present in this PR.

This PR fixes a warning:
```
"inject-loader@3.0.0" has incorrect peer dependency "webpack@^1 || ^2"
```

This was the main intent of the PR. But I figured, while I am at it, might as well update the rest

### CODE REVIEW

**Comment by sudo-suhas** [comment]
ping @yyx990803

**Comment by yyx990803** [comment]
Thanks! Although I'm wondering if patch bumps are necessary since we are using a semver range with `^` - users automatically get the latest patch.

**Comment by sudo-suhas** [comment]
Probably not for the end users. But the lock file will mean that collaborators will install older versions.

**Comment by yyx990803** [comment]
That's true. Would you mind resolving the conflicts (we just released a hotfix)?

**Comment by sudo-suhas** [comment]
Sure, no problem. Is it alright if I do it by tomorrow?

**Comment by yyx990803** [comment]
Sure! Take your time.

**Comment by sudo-suhas** [comment]
@yyx990803 Rebase done.

**Comment by yyx990803** [comment]
Mind removing `.vscode` from the PR?

**Comment by sudo-suhas** [comment]
My apologies! Doing it now.

**Comment by sudo-suhas** [comment]
I have removed `.vscode` from the PR. I added it by mistake while rebasing.

**Comment by yyx990803** [comment]
Thanks!

**Comment by sudo-suhas** [comment]
I love working with Vue.js and very very happy to help!

**Pull request merged**
