### PR TITLE
chore: add missing dependencies

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Required for pnpm compatibility.

For full compatibility, https://github.com/vuejs/vue-style-loader/pull/24 is also needed.

### CODE REVIEW

**Comment by yyx990803** [comment]
Does `pnpm` allow requiring from peer deps? It doesn't make sense for `vue-loader` to have wepback as a dependency.

**Comment by ishitatsuyuki** [comment]
@yyx990803 Done.

**Comment by znck** [comment]
Yes, it does allow accessing `peer` dependencies.

**Comment by IlyaSemenov** [comment]
Vue is unusable without `webpack` as a peer dependency with `pnpm`. Can this be merged?

**Comment by manniL** [comment]
There are merge conflicts now

**Pull request merged**
