### PR TITLE
Support for srcset

### PR DESCRIPTION
**Pull request by AndreKR**
This PR adds support for ``. The `srcset` URLs are converted to `require()`s, just as `` is, the descriptors stay untouched.

### CODE REVIEW

**Comment by narrowtux** [comment]
Would love to have this pulled, when can I expect this?

**Comment by AndreKR** [comment]
As a workaround I'm currently putting
```json
"vue-loader": "AndreKR/vue-loader#srcset",
```
in my package.json.

Note however, that I'm not actively monitoring `vuejs/vue-loader` to pull in updates.

**Comment by therealpecus** [comment]
Hi @AndreKr,
thank you for this. We tested it and discovered a couple of issues: your code does not take into account attributes spawning multiple lines, and `srcset` attributes on `source` tags (useful for `picture` elements).

I made a quick review of your code that I submitted as a PR, but I think credit fir this should be yours, so feel free to review them and update this PR.

For all of those that can't wait, see https://github.com/therealpecus/vue-loader `srcset` branch.

**Comment by AndreKR** [comment]
@therealpecus Thanks for the fixes, I cherry-picked your commit into this branch. I found another issue with whitespace within the candidates. I also added a test for [all three cases](https://github.com/vuejs/vue-loader/pull/953/commits/d31d0976ab78a534eb2816c83590779822e87c68#diff-969754c85777905d6fcc43c2dd062a7cR7). Please check again.

**Comment by therealpecus** [comment]
Hopefully this will speed up the approval process. Thanks for the further review!

**Comment by assembledadam** [comment]
Any word on merging this? Thanks.

**Comment by narrowtux** [comment]
bump

**Comment by assembledadam** [comment]
Whilst this was merged, it doesn't appear to be in any stable version of vuejs loader... I'm still having to use AndreKR's forked version.

**Comment by gburning** [comment]
Any word on how to get this working?

**Comment by theolavaux** [comment]
Still no support `srcset` in Oct, 2020?

**Pull request merged**
