### PR TITLE
[Feature]loader option accepts function

### PR DESCRIPTION
**Pull request by xjchengo**
This PR aims at addressing the problem of #531.

### CODE REVIEW

**Comment by kazupon** [comment]
Thank you for your PR!
Sorry for the late reply.

Please resolve the conflict.

**Comment by kazupon** [comment]
> Please resolve the conflict.

never mind, I fixed it.

**Comment by xjchengo** [comment]
Sometimes, we need to overwrite default html loaders. But in webpack config, we cannot access to module id. So if default html loaders are overwritten, hot-reload feature will miss.

**Comment by yyx990803** [comment]
Closing due to inactivity - we are also in feature freeze for v14 and below. Thanks for the PR.

**Pull request closed without merging**
