### PR TITLE
Support css modules at front/server side

### PR DESCRIPTION
**Pull request by PowerfulPony**
work depends on the following revisions

* Add support attribute module - vue-template-compiler
https://github.com/vuejs/vue/pull/4091
* Do not add a handler on the server
https://github.com/vuejs/vue-style-loader/pull/1

### CODE REVIEW

**Comment by PowerfulPony** [comment]
Just due to the need to use "css modules" at SSR

These changes are possible because of @YiSiWang
https://github.com/vuejs/vue-loader/pull/422
https://github.com/vuejs/vue-loader/pull/331

**Comment by yyx990803** [comment]
Is there any change in this PR that is not covered / needs to be addressed in #422 ? - would it be better if we merge the two dependent PRs and then merge #422 instead?

**Comment by PowerfulPony** [comment]
+It works with SSR
+The server-bundle fall only css modules
+css modules are named according to the attribute of the module
Because styles are loaded through vue-style-loader, it is necessary to fix the fragment associated with the addition of hot.reload script https://github.com/vuejs/vue-style-loader/pull/1
Cause the server to will throw an error because the browser checks

In this PR are implemented that was available in version 8, there is also support for SSR.
Important to me only anyside support css-module, since using SSR.

It is also possible to fully restore the documentation of version 8
https://github.com/vuejs/vue-loader/pull/331

I am for the result!
I just want to pay attention to the css-modules, in the name of the module, and ssr

**Comment by YiSiWang** [comment]
@PowerfulPony Thank you for pointing out problems with SSR. But I think it's better to drop `style-loader` when in SSR.

1. Faster && less code
2. No need for vuejs/vue-style-loader#1

I've done it in #422 with test case.

**Comment by PowerfulPony** [comment]
@YiSiWang 
Yes, such a solution is better
https://github.com/vuejs/vue/pull/4091 Please pay attention, it is already possible to use the attribute in dev branch

**Comment by yyx990803** [comment]
In that case, closing this in favor of #422

**Pull request closed without merging**
